[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags = -Wno-unknown-pragmas -DSERIAL_RX_BUFFER_SIZE=128

; upload_port = /dev/ttyUSB*
; monitor_port = /dev/ttyUSB*
upload_port = /dev/cu.usbserial*
monitor_port = /dev/cu.usbserial*
; upload_port = /dev/cu.usbserial-1412330
; monitor_port = /dev/cu.usbserial-1412330

lib_deps =
    fastled/FastLED@^3.6.0

[env:native]
platform = native
test_framework = unity
build_flags = -DUNIT_TEST
test_build_src = false
